PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gtaa: <http://data.beeldengeluid.nl/gtaa/>
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?concept ?prefLabel (GROUP_CONCAT(?label; SEPARATOR=" ") AS ?labels)
WHERE {
    ?concept a skos:Concept ;
             skos:inScheme gtaa:Onderwerpen ;
             skos:prefLabel ?prefLabel .
  
  FILTER(LANG(?prefLabel) = 'nl')

  OPTIONAL { ?concept skosxl:altLabel/skosxl:literalForm ?label . }
  
  #OPTIONAL { ?concept skos:broader ?broader . ?broader a skos:Concept ; skos:prefLabel ?broaderLabel .}
  #OPTIONAL { ?concept skos:related ?related .  ?related a skos:Concept ; skos:prefLabel ?relatedLabel .}
} GROUP BY ?concept ?prefLabel ORDER BY ?prefLabel
